# Generated by Django 4.1.7 on 2023-03-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='tds',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='ec',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
